### ISSUE TITLE
Update the placeholder tenant sample used in create panel

### ISSUE THREAD

**Issue by bsctl** [clastix/kamaji-console#69]
Update the placeholder tenant sample used in create panel as following:

```yaml
apiVersion: kamaji.clastix.io/v1alpha1
kind: TenantControlPlane
metadata:
  name: #name
  namespace: #namespace
spec:
  dataStore: default
  controlPlane:
    deployment:
      replicas: 2
    service:
      serviceType: LoadBalancer
  kubernetes:
    version: v1.25.2
    kubelet:
      cgroupfs: systemd
  networkProfile:
    port: 6443
  addons:
    coreDNS: {}
    kubeProxy: {}
    konnectivity:
      server:
        port: 8132 
        resources: {}
      agent: {}
```
